spring:

---
spring:
  profiles: local

security:
  jwt:
    key-store: classpath:security/jwt.jks
    key-store-password: 1q2w3e4r
    key-pair-alias: jake
    key-pair-password: park

---
spring:
  profiles: alpha

security:
  jwt:
    key-store:
    key-store-password:
    key-pair-alias:
    key-pair-password: