spring:

---
spring:
  profiles: local

security:
  jwt:
    key-store: classpath:security/keystore.jks
    key-store-password: letmein
    key-pair-alias: mytestkey
    key-pair-password: changeme

---
spring:
  profiles: alpha

security:
  jwt:
    key-store:
    key-store-password:
    key-pair-alias:
    key-pair-password: